const fs=require("fs");
const F="C:/Users/admin/Downloads/madisonmarketreportseptember2026.html";
let s=fs.readFileSync(F,"utf8");
const OLD="Month-by-month history is shown in the year-over-year comparison above and in the full data section.";
const NEW="Year-over-year comparisons against the same month last year are shown above, and current supply, price-range, and zip-level detail is in the full data section.";
if(!s.includes(OLD)) throw new Error("target sentence not found");
if(s.split(OLD).length!==2) throw new Error("sentence appears more than once");
s=s.split(OLD).join(NEW);
fs.writeFileSync(F,s,"utf8");
console.log("replaced 1 occurrence");
console.log("em dashes in file:",(s.match(/\u2014/g)||[]).length);
